### ISSUE TITLE
radio运行一段时间后会让服务挂掉 

### ISSUE THREAD

**Issue by hdcola** [HDCodePractice/MusicPlayer#1]

**Comment by Sichengthebest** [comment]
谁是 @networkextension

**Comment by hdcola** [comment]
> 谁是 @networkextension

不知道啊

**Comment by hdcola** [comment]
其实不是挂掉 /restart 可以重启，原因是ffmpeg得到了这样的提示
 Server returned 403 Forbidden (access denied)

**Comment by hdcola** [comment]
使用 #25 策略这个issue close
